#Base URL
baseURL = https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F
#LogIn Page Data
validEmail = admin@yourstore.com
validPSW = admin
invalidEmail = admin1234@yourstore.comk
invalidPSW = admin1234
errorMessage = Login was unsuccessful. Please correct the errors and try again.
#Add New Customer Page Data
errorMessageWithEmptyForm = Valid Email is required for customer to be in 'Registered' role
